//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPosApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProdID { get; set; }
        public string PCode { get; set; }
        public string Barcode { get; set; }
        public string Manufactor { get; set; }
        public string Model { get; set; }
        public string Full_Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Year { get; set; }
        public string Warranty { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Reorder { get; set; }
        public string Dealer { get; set; }
        public string Img { get; set; }
        public Nullable<System.DateTime> added_time { get; set; }
        public Nullable<int> added_by { get; set; }
    }
}
